### ISSUE TITLE
Feature request: post install script to move packages to the right directory on initial install

### ISSUE THREAD

**Issue by barthje** [oomphinc/composer-installers-extender#11]
Hello,

If you 'composer require composer-installers-extender' composer require a package that has a different install path but is installed before composer-installers-extender is installed it will not be placed in the correct directory.

Maybe a post install script could be created to read the installer types and the packages and move them if they are not installed in the correct directory(because the installer is installed after the package is installed)

**Comment by frederickjh** [comment]
@barthje you can run:
```
composer update --lock
```
This will update the lock file hash and because it has changed then install them, however I find that it does not clean up the old directories and you need to manually remove them.

**Comment by frederickjh** [comment]
So, if  the above method is recommended then we just need a way to clean up the folders that were abandoned by the change in location.
