### ISSUE TITLE
Symbolic link?

### ISSUE THREAD

**Issue by ghost** [oomphinc/composer-installers-extender#12]
Hi!

Symbolic links seem to not be supported. When using a path repository:

```json
    "repositories": [
        {
            "type": "path",
            "url": "../some/path"
        }
    ],
```

Composer (when used without custom installer) creates a symlink, unless the option `"symlink": false` is used (see: https://github.com/composer/composer/issues/4636#issuecomment-188750882).

Composer-installers-extender breaks this behaviour and, therefore, consistency. When using path repository, the package is expected to be symlinked, not mirrored.

**Comment by ghost** [comment]
I must be very tired... it does create a symbolic link (yeah, 1 hour to realize that...)

**Comment by balbuf** [comment]
Good to hear that it works as required! :)
