### ISSUE TITLE
feature request add installed items to .gitignore

### ISSUE THREAD

**Issue by tkegan** [oomphinc/composer-installers-extender#13]
I have begun using your composer-installers-extender in a project type package to install modules into sensible paths as needed so first of all thank you. However I have had to add the modules that I have installed to the package's .gitignore manually so that the modules stay out of my git repo. It would be wonderful if modules could be automatically added to the .gitignore perhaps controlled by a config/extra key.

**Comment by balbuf** [comment]
Hi @tkegan!

This request is out of the scope of this package, which is solely devoted to allowing other packages to be installed in any arbitrary location. I do see how the needs are related, but this request would be better suited for its own package, especially considering users may use any number of other methods besides git to store their projects.

**Comment by johnpicozzi** [comment]
Closing as @balbuf comment about people using something other than git makes sense.
