### ISSUE TITLE
Have to run composer install twice - with version 1.8.0

### ISSUE THREAD

**Issue by sanddevil** [oomphinc/composer-installers-extender#18]
Hi there - this is very similar to issue 6 referenced https://github.com/oomphinc/composer-installers-extender/issues/6 but I am using `composer 1.8.0` which according to the other ticket should have fixed this issue. I have to run composer twice for my packages to be installed. The `drupal/drupal` core product always installs, but the `ckeditor/ckeditor` only gets installed on the second run. 

I have pared down my composer file to show the phenomenon easily. 

```
{
  "name": "Nigel Test",
  "license": "proprietary",
  "minimum-stability": "dev",
  "prefer-stable": true,
  "description": "Test",
  "version": "0.0.1",
  "repositories": [
      {
        "type": "composer",
        "url": "https://packages.drupal.org/7"
      }
  ],
  "require": {
    "oomphinc/composer-installers-extender": "^1.1",
    "ckeditor/ckeditor": "4.5.11",
    "drupal/drupal": "^7.59"
  },
  "extra": {
    "installer-types": ["library"],
    "installer-paths": {
      "docroot": ["drupal/drupal"],
      "docroot/sites/all/libraries/ckeditor": ["ckeditor/ckeditor"]
    }
  },
  "scripts": {
  },
  "config": {
    "platform": {
      "php": "7.1"
    }
  }
}
```
If I remove the `drupal/drupal `package from the json, the `ckeditor` package is installed ok. Whether the `drupal/drupal` is above or below the `ckeditor/ckeditor` makes no difference. 

Worth noting is `drupal/drupal` will create a directory `docroot/sites/all/libraries` and place a `README.txt` file within it. `ckeditor/ckeditor` should also create a directory `docroot/sites/all/libraries` and place `ckeditor` package within it. I don't know if there is an interference between the two but `drupal/drupal` always gets created. 

Any ideas appreciated! Many thanks in advance.

**Comment by leonk** [comment]
Experiencing the same issue.  Any directory being used for a custom installer path that is also created by `drupal/drupal`, will have the package wiped (and replaced with the drupal core empty directory and README file).  Running `composer install` twice will result in the package downloading.

A few more observations:
- Modifying the composer.lock file to add a dependency on `drupal/drupal` to `ckeditor/ckeditor` fixes the issue (not recommending as a solution, but it's worth noting).
- I couldn't replicate this issue when using Drupal 8 and `drupal/core`.  Not sure what exactly is the difference causing the issue (I first thought drupal-scaffold was doing something, but I tried removing that and it still worked).

Anyway, solution I am going with is using the https://github.com/drupal-composer/preserve-paths plugin, and specifying `docroot/sites/all/libraries` as a path to preserve.
