### ISSUE TITLE
Add 2.0.0 tag and update changelog

### ISSUE THREAD

**Issue by nathandentzau** [oomphinc/composer-installers-extender#24]
Please create a new 2.0.0 tag with [the changes merged into master](https://github.com/oomphinc/composer-installers-extender/commit/081bdaee2d12f0355e63b3c9d38ca0e9ea221d93) and update the changelog when cutting a new release. 

[This commit](https://github.com/oomphinc/composer-installers-extender/commit/9ddcdb79ab738e055c04625d372db9db781b7c05) also needs a changelog entry.

Thanks!

**Comment by johnpicozzi** [comment]
All set!
