### ISSUE TITLE
Requirement of PHP 7.1 is not a good idea for a composer plugin

### ISSUE THREAD

**Issue by damienlaguerre** [oomphinc/composer-installers-extender#31]
The Composer 2.0 still supports PHP 5.3 and above, much like Composer 1.x

As composer plugin, the best practice is to stay compatible with the same version of the main project.

**Comment by mstrelan** [comment]
I don't want to be using old PHP versions but for particular reasons beyond my control we're using PHP 7.0 somewhere and projects using this plugin won't install. But I appreciate the inefficiency in supporting EOL versions so I don't expect this to be resolved.

**Comment by damienlaguerre** [comment]
I've made a Fork to fight with this issue.

You can review it: damienlaguerre/composer-installers-extender
