### ISSUE TITLE
Platform Requirements

### ISSUE THREAD

**Issue by XedinUnknown** [oomphinc/composer-installers-extender#9]
Hi,

And thank you for this great work, which is very useful, and something that I was expecting from `composer/installers`, to be quite honest.

However, I would like to point out that there are no minimal requirements defined anywhere. For this reason, I had no idea that it would not work in my PHP 5.3 project: the minimal PHP version is neither in the  readme, nor in the Composer configuration. I suggest that you add the minimal required PHP version to both places.

Another point is the PHP version itself. In a PHP 5.3 environment, `composer update -vvv` gives the following error:

> Loading plugin OomphInc\ComposerInstallersExtender\Plugin
> PHP Parse error:  syntax error, unexpected '[' in /path/to/project/vendor\oomphinc\composer-installers-extender\src\InstallerHelper.php on line 12

The reason for this is the PHP 5.4 array syntax used in the indicated location. This is the only thing that makes your package incompatible with PHP 5.3. Would you be so kind as to convert that syntax to be compatible with PHP 5.3, e.g. `array( false )`, and set the minimal required PHP version to at least PHP 5.3.9? I have confirmed this to work in a PHP 5.3.29 environment, and cannot testify whether or not it would work for 5.3.9. However, there's quite an important [bug](https://bugs.php.net/bug.php?id=43200) fixed in PHP 5.3.9 that has to do with "overloading" of abstract methods, and everything should work from that point onward. Of course, if you manage to test with an even lower version, that would be even better. If everything is compatible with a low PHP version, there's no reason why this shouldn't be allowed. Right? :) Thanks!

**Comment by raubin** [comment]
Hi @XedinUnknown - Thanks for pointing that out! We'll have a look and see if support for older versions of PHP is something we can support. Either way, we'll be sure to add minimum requirements, so no one else gets hung up on this! 🚀

**Comment by XedinUnknown** [comment]
Hi @raubin, and thank you for your super-quick reply!

If you could test and merge this within the next few days, that would be absolutely awesome, since this is a pre-requisite for something I am working on, and I really don't want to fork a project just for the sake of arranging some brackets. I would much prefer this repository to be the authoritative source for all such (very useful) functionality. Please let me know if there is something I can do to speed things up.

**Comment by balbuf** [comment]
Resolved as of #10
